
= Sign up

https://manage.openshift.com/

Sign up for the Free platform.  Pick your region.  Wait for activation email (signups are throttled during times of heavy activity)


= Create the project

== Using the Web UI

I signed up in starter-us-east-1, so log in here

https://console.starter-us-east-1.openshift.com/console/catalog

Select the python app,

Project: pyramid    (must be unique across all users)

Python: we're using 3.6

App name: climbing  (must be unique within project)

Git repo: https://github.com/dsb3/pyramid.git (fork this first if you want to make your own edits)

Click "ok"

Wait for the project to build and deploy.


== Using the command line

Download the "oc" tool.

Log in to the web ui (above) to get your "oc whoami" credentials

oc new-app .....



= Add Health Checks

Deployments -> appname -> Edit Health Checks

Readiness Probe and Livliness Probe:

Set both to HTTP GET, /health, timeout 1.


= Add Github build hook

*Only do this if you've forked the repo - you can't trigger on mine*

Builds -> appname -> Configuration

Copy the "Github Webhook URL", which will look something like:

https://api.starter-us-east-1.openshift.com/oapi/v1/namespaces/pyramid/buildconfigs/climbing/webhooks/xxxx/github

Go to github repository.  Settings -> Webhooks -> Add webhook

Paste in the payload URL.  Set application/json.  Leave Secret blank, "just the push event", "Add webhook"

The webhook should fire immediately, and again on every push, generating a build
and redeploy.



= Override Configuration

See the configuration doc for creating a Config Map to override the bundled
config.yml.


= Viewing

For my sample, it's at 

http://climbing-pyramid.1d35.starter-us-east-1.openshiftapps.com/


= Updating the application

Github can create a webhook directly to the openshift cluster to redeploy
on changes.


== Manual

Builds -> builds -> Build -> "Start Build"


== Automatic

TBD


= Configuring data sources

The default data source is embedded in the git repo.  To change this, fork
and edit the repo, or (preferred) is to make use of a secret to override
the default data.




