---
# If you create a file /data/config.yml and it will overwrite/replace this in the running container
default:
  dave
pages:
  dave:          1MU9vmWep4GDHleJo6Tw0BJb4fo0XjVJuz1p9uYgCrpg/0
  dave-boulder:  1MU9vmWep4GDHleJo6Tw0BJb4fo0XjVJuz1p9uYgCrpg/1825018984
  dave-rock:     1MU9vmWep4GDHleJo6Tw0BJb4fo0XjVJuz1p9uYgCrpg/447635240

